//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.23 at 02:38:43 PM IST 
//


package com.alfaris.ipsh.soapService;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.alfaris.ipsh.soapService package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.alfaris.ipsh.soapService
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllEmployeeResponse }
     * 
     */
    public GetAllEmployeeResponse createGetAllEmployeeResponse() {
        return new GetAllEmployeeResponse();
    }

    /**
     * Create an instance of {@link SearchEmployeeResponse }
     * 
     */
    public SearchEmployeeResponse createSearchEmployeeResponse() {
        return new SearchEmployeeResponse();
    }

    /**
     * Create an instance of {@link SearchEmployeeResponse.AaData }
     * 
     */
    public SearchEmployeeResponse.AaData createSearchEmployeeResponseAaData() {
        return new SearchEmployeeResponse.AaData();
    }

    /**
     * Create an instance of {@link AddEmployeeRequest }
     * 
     */
    public AddEmployeeRequest createAddEmployeeRequest() {
        return new AddEmployeeRequest();
    }

    /**
     * Create an instance of {@link com.alfaris.ipsh.soapService.EmployeeInfo }
     * 
     */
    public com.alfaris.ipsh.soapService.EmployeeInfo createEmployeeInfo() {
        return new com.alfaris.ipsh.soapService.EmployeeInfo();
    }

    /**
     * Create an instance of {@link AddEmployeeResponse }
     * 
     */
    public AddEmployeeResponse createAddEmployeeResponse() {
        return new AddEmployeeResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link GetEmployeeByIdRequest }
     * 
     */
    public GetEmployeeByIdRequest createGetEmployeeByIdRequest() {
        return new GetEmployeeByIdRequest();
    }

    /**
     * Create an instance of {@link GetEmployeeResponse }
     * 
     */
    public GetEmployeeResponse createGetEmployeeResponse() {
        return new GetEmployeeResponse();
    }

    /**
     * Create an instance of {@link UpdateEmployeeRequest }
     * 
     */
    public UpdateEmployeeRequest createUpdateEmployeeRequest() {
        return new UpdateEmployeeRequest();
    }

    /**
     * Create an instance of {@link UpdateEmployeeResponse }
     * 
     */
    public UpdateEmployeeResponse createUpdateEmployeeResponse() {
        return new UpdateEmployeeResponse();
    }

    /**
     * Create an instance of {@link DeleteEmployeeRequest }
     * 
     */
    public DeleteEmployeeRequest createDeleteEmployeeRequest() {
        return new DeleteEmployeeRequest();
    }

    /**
     * Create an instance of {@link DeleteEmployeeResponse }
     * 
     */
    public DeleteEmployeeResponse createDeleteEmployeeResponse() {
        return new DeleteEmployeeResponse();
    }

    /**
     * Create an instance of {@link GetAllEmployeeRequest }
     * 
     */
    public GetAllEmployeeRequest createGetAllEmployeeRequest() {
        return new GetAllEmployeeRequest();
    }

    /**
     * Create an instance of {@link GetAllEmployeeResponse.EmployeeInfo }
     * 
     */
    public GetAllEmployeeResponse.EmployeeInfo createGetAllEmployeeResponseEmployeeInfo() {
        return new GetAllEmployeeResponse.EmployeeInfo();
    }

    /**
     * Create an instance of {@link SearchEmployeeRequest }
     * 
     */
    public SearchEmployeeRequest createSearchEmployeeRequest() {
        return new SearchEmployeeRequest();
    }

    /**
     * Create an instance of {@link SearchEmployeeResponse.AaData.EmployeeInfo }
     * 
     */
    public SearchEmployeeResponse.AaData.EmployeeInfo createSearchEmployeeResponseAaDataEmployeeInfo() {
        return new SearchEmployeeResponse.AaData.EmployeeInfo();
    }

}
