//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.23 at 02:38:43 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://com.alfaris.ipsh.soapService.allapis", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.alfaris.ipsh.soapService;
