//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.23 at 02:38:43 PM IST 
//


package com.alfaris.ipsh.soapService;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aaData"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="employeeInfo" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="employeeId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="department" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="iTotalDisplayRecord" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="iTotalRecord" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aaData",
    "iTotalDisplayRecord",
    "iTotalRecord"
})
@XmlRootElement(name = "searchEmployeeResponse")
public class SearchEmployeeResponse {

    @XmlElement(required = true)
    protected SearchEmployeeResponse.AaData aaData;
    protected long iTotalDisplayRecord;
    protected long iTotalRecord;

    /**
     * Gets the value of the aaData property.
     * 
     * @return
     *     possible object is
     *     {@link SearchEmployeeResponse.AaData }
     *     
     */
    public SearchEmployeeResponse.AaData getAaData() {
        return aaData;
    }

    /**
     * Sets the value of the aaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchEmployeeResponse.AaData }
     *     
     */
    public void setAaData(SearchEmployeeResponse.AaData value) {
        this.aaData = value;
    }

    /**
     * Gets the value of the iTotalDisplayRecord property.
     * 
     */
    public long getITotalDisplayRecord() {
        return iTotalDisplayRecord;
    }

    /**
     * Sets the value of the iTotalDisplayRecord property.
     * 
     */
    public void setITotalDisplayRecord(long value) {
        this.iTotalDisplayRecord = value;
    }

    /**
     * Gets the value of the iTotalRecord property.
     * 
     */
    public long getITotalRecord() {
        return iTotalRecord;
    }

    /**
     * Sets the value of the iTotalRecord property.
     * 
     */
    public void setITotalRecord(long value) {
        this.iTotalRecord = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="employeeInfo" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="employeeId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="department" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employeeInfo"
    })
    public static class AaData {

        @XmlElement(required = true)
        protected List<SearchEmployeeResponse.AaData.EmployeeInfo> employeeInfo;

        /**
         * Gets the value of the employeeInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the employeeInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmployeeInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SearchEmployeeResponse.AaData.EmployeeInfo }
         * 
         * 
         */
        public List<SearchEmployeeResponse.AaData.EmployeeInfo> getEmployeeInfo() {
            if (employeeInfo == null) {
                employeeInfo = new ArrayList<SearchEmployeeResponse.AaData.EmployeeInfo>();
            }
            return this.employeeInfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="employeeId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="department" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "employeeId",
            "name",
            "department",
            "phone",
            "address"
        })
        public static class EmployeeInfo {

            protected long employeeId;
            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String department;
            @XmlElement(required = true)
            protected String phone;
            @XmlElement(required = true)
            protected String address;

            /**
             * Gets the value of the employeeId property.
             * 
             */
            public long getEmployeeId() {
                return employeeId;
            }

            /**
             * Sets the value of the employeeId property.
             * 
             */
            public void setEmployeeId(long value) {
                this.employeeId = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the department property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDepartment() {
                return department;
            }

            /**
             * Sets the value of the department property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDepartment(String value) {
                this.department = value;
            }

            /**
             * Gets the value of the phone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPhone() {
                return phone;
            }

            /**
             * Sets the value of the phone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPhone(String value) {
                this.phone = value;
            }

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress(String value) {
                this.address = value;
            }

        }

    }

}
